import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>COBSEA</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div id="landing">
        <Image src="/cobsea.svg" alt="COBSEA" width={162} height={42} />
      </div>
    </div>
  )
}
